### Login (JWT)
POST http://127.0.0.1:8000/api/accounts/auth/login/
Content-Type: application/json

{
  "email": "mubiru.shamuranahamada@students.mak.ac.ug",
  "password": "shamuran18100"
}

### send invite
POST http://127.0.0.1:8000/api/accounts/lecturers/invite/
Content-Type: application/json
Authorization: Bearer 

{
  "email": "kiwalabyeo@gmail.com"
}