# Generated by Django 6.0.1 on 2026-03-04 08:24

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SUPERADMIN", "Super Admin"),
                            ("LECTURER", "Lecturer"),
                            ("STUDENT", "Student"),
                        ],
                        default="STUDENT",
                        max_length=16,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="LabSeries",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("code", models.CharField(blank=True, max_length=64)),
                (
                    "year",
                    models.PositiveIntegerField(
                        default=2026,
                        validators=[django.core.validators.MinValueValidator(2000)],
                    ),
                ),
                ("semester", models.CharField(blank=True, max_length=32)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The lecturer who owns/manages this lab series.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_labseries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LecturerProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=120)),
                ("staff_id", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecturer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Roster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("LOCKED", "Locked")],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lab_series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rosters",
                        to="accounts.labseries",
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locked_rosters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=64)),
                ("capacity", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "roster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="accounts.roster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RosterEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("reg_no", models.CharField(blank=True, max_length=64)),
                ("program", models.CharField(blank=True, max_length=120)),
                ("gender", models.CharField(blank=True, max_length=32)),
                ("is_removed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="accounts.group",
                    ),
                ),
                (
                    "roster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="accounts.roster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccountClaim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("LECTURER_INVITE", "Lecturer Invite"),
                            ("STUDENT_REDEEM", "Student Redeem"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "role_to_assign",
                    models.CharField(
                        choices=[
                            ("SUPERADMIN", "Super Admin"),
                            ("LECTURER", "Lecturer"),
                            ("STUDENT", "Student"),
                        ],
                        max_length=16,
                    ),
                ),
                ("otp_hash", models.CharField(max_length=128)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "roster_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="claims",
                        to="accounts.rosterentry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "roster_entry",
                    models.OneToOneField(
                        help_text="The locked roster row this student account is bound to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_profile",
                        to="accounts.rosterentry",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="labseries",
            index=models.Index(fields=["owner"], name="accounts_la_owner_i_3bd094_idx"),
        ),
        migrations.AddIndex(
            model_name="labseries",
            index=models.Index(fields=["code"], name="accounts_la_code_144649_idx"),
        ),
        migrations.AddIndex(
            model_name="roster",
            index=models.Index(
                fields=["lab_series", "status"], name="accounts_ro_lab_ser_68c177_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roster",
            index=models.Index(
                fields=["lab_series", "version"], name="accounts_ro_lab_ser_9c2ffe_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="roster",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "DRAFT")),
                fields=("lab_series", "status"),
                name="uniq_draft_roster_per_lab_series",
            ),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(
                fields=["roster", "label"], name="accounts_gr_roster__15ab84_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="group",
            constraint=models.UniqueConstraint(
                fields=("roster", "label"), name="uniq_group_label_per_roster"
            ),
        ),
        migrations.AddIndex(
            model_name="rosterentry",
            index=models.Index(fields=["email"], name="accounts_ro_email_b64072_idx"),
        ),
        migrations.AddIndex(
            model_name="rosterentry",
            index=models.Index(
                fields=["roster", "email"], name="accounts_ro_roster__85c1b6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="rosterentry",
            constraint=models.UniqueConstraint(
                fields=("roster", "email"), name="uniq_email_per_roster"
            ),
        ),
        migrations.AddIndex(
            model_name="accountclaim",
            index=models.Index(
                fields=["email", "purpose"], name="accounts_ac_email_000901_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accountclaim",
            index=models.Index(
                fields=["expires_at"], name="accounts_ac_expires_27dcba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accountclaim",
            index=models.Index(
                fields=["is_used"], name="accounts_ac_is_used_64337f_idx"
            ),
        ),
    ]
