# Generated by Django 6.0.1 on 2026-03-04 09:39

import accounts.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", accounts.managers.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="accountclaim",
            name="otp_hash",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
